### ISSUE TITLE
Fix the affix bottom functionality

### ISSUE THREAD

**Issue by elessar-ch** [axa-ch/style-guide#375]

**Comment by davidknezic** [comment]
The `affix` plugin doesn't handle the bottom case well. This should be fixed.

We should also consider rewriting it so it's stream based, to reduce intermediate states. And change to es2015!

**Comment by AndyOGo** [comment]
@davidknezic @elessar-ch 
I guess this one is still an issue?

**Comment by davidknezic** [comment]
Yes, still an issue.
